# Generated by Django 2.0.4 on 2018-07-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180709_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='date_published',
        ),
    ]
