# Generated by Django 2.0.4 on 2018-07-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='date_published',
        ),
    ]
